# Generated by Django 4.2 on 2023-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='themes',
            field=models.CharField(choices=[('PL', 'Политика'), ('CL', 'Культура'), ('SC', 'Общество'), ('EC', 'Экономика')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.CharField(choices=[('PL', 'Политика'), ('CL', 'Культура'), ('SC', 'Общество'), ('EC', 'Экономика')], max_length=2),
        ),
    ]
