# Generated by Django 4.2 on 2023-04-06 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_author_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='themes',
            field=models.CharField(choices=[('WD', 'Мир'), ('PL', 'Политика'), ('BS', 'Бизнес'), ('HL', 'Здоровье'), ('CL', 'Культура'), ('SC', 'Общество'), ('AC', 'Проишествия'), ('SP', 'Спорт'), ('IT', 'ИТ'), ('SN', 'Наука'), ('EC', 'Экономика')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2),
        ),
    ]
