# Generated by Django 4.2 on 2023-04-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_alter_author_author_alter_category_themes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='themes',
            field=models.CharField(choices=[('PL', 'Политика'), ('CL', 'Культура'), ('SC', 'Общество'), ('EC', 'Экономика')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.CharField(choices=[('PL', 'Политика'), ('CL', 'Культура'), ('SC', 'Общество'), ('EC', 'Экономика')], max_length=2),
        ),
    ]
